import type { ProviderInfo } from './types';

export const DEFAULT_PROVIDERS: ProviderInfo[] = [
  { name: 'WandB', slug: 'wandb' },
  { name: 'Z.AI', slug: 'z-ai' },
  { name: 'Stealth', slug: 'stealth' },
  { name: 'Arcee AI', slug: 'arcee-ai' },
  { name: 'Cerebras', slug: 'cerebras' },
  { name: 'Venice', slug: 'venice' },
  { name: 'OpenAI', slug: 'openai' },
  { name: 'Morph', slug: 'morph' },
  { name: 'Moonshot AI', slug: 'moonshotai' },
  { name: 'SambaNova', slug: 'sambanova' },
  { name: 'BaseTen', slug: 'baseten' },
  { name: 'Fireworks', slug: 'fireworks' },
  { name: 'NextBit', slug: 'nextbit' },
  { name: 'AI21', slug: 'ai21' },
  { name: 'Black Forest Labs', slug: 'black-forest-labs' },
  { name: 'Featherless', slug: 'featherless' },
  { name: 'Minimax', slug: 'minimax' },
  { name: 'Groq', slug: 'groq' },
  { name: 'Mancer 2', slug: 'mancer' },
  { name: 'Azure', slug: 'azure' },
  { name: 'Hyperbolic', slug: 'hyperbolic' },
  { name: 'NCompass', slug: 'ncompass' },
  { name: 'StreamLake', slug: 'streamlake' },
  { name: 'Crusoe', slug: 'crusoe' },
  { name: 'Cohere', slug: 'cohere' },
  { name: 'DeepSeek', slug: 'deepseek' },
  { name: 'Perplexity', slug: 'perplexity' },
  { name: 'SiliconFlow', slug: 'siliconflow' },
  { name: 'Avian', slug: 'avian' },
  { name: 'Novita', slug: 'novita' },
  { name: 'Switchpoint', slug: 'switchpoint' },
  { name: 'xAI', slug: 'xai' },
  { name: 'Inflection', slug: 'inflection' },
  { name: 'DeepInfra', slug: 'deepinfra' },
  { name: 'InferenceNet', slug: 'inference-net' },
  { name: 'Amazon Nova', slug: 'amazon-nova' },
  { name: 'Xiaomi', slug: 'xiaomi' },
  { name: 'Mara', slug: 'mara' },
  { name: 'Sourceful', slug: 'sourceful' },
  { name: 'Inception', slug: 'inception' },
  { name: 'Nvidia', slug: 'nvidia' },
  { name: 'Alibaba', slug: 'alibaba' },
  { name: 'Friendli', slug: 'friendli' },
  { name: 'Infermatic', slug: 'infermatic' },
  { name: 'Mistral', slug: 'mistral' },
  { name: 'AionLabs', slug: 'aion-labs' },
  { name: 'Nebius', slug: 'nebius' },
  { name: 'Cloudflare', slug: 'cloudflare' },
  { name: 'Liquid', slug: 'liquid' },
  { name: 'Phala', slug: 'phala' },
  { name: 'OpenInference', slug: 'open-inference' },
  { name: 'GMICloud', slug: 'gmicloud' },
  { name: 'Parasail', slug: 'parasail' },
  { name: 'Relace', slug: 'relace' },
  { name: 'Clarifai', slug: 'clarifai' },
  { name: 'FakeProvider', slug: 'fake-provider' },
  { name: 'Chutes', slug: 'chutes' },
  { name: 'Seed', slug: 'seed' },
  { name: 'Amazon Bedrock', slug: 'amazon-bedrock' },
  { name: 'Anthropic', slug: 'anthropic' },
  { name: 'Modular', slug: 'modular' },
  { name: 'ModelRun', slug: 'modelrun' },
  { name: 'Cirrascale', slug: 'cirrascale' },
  { name: 'AtlasCloud', slug: 'atlas-cloud' },
  { name: 'Google', slug: 'google-vertex' },
  { name: 'Google AI Studio', slug: 'google-ai-studio' },
  { name: 'Together', slug: 'together' },
];
